@isTest
 public   class CMPLFeedItemTriggerTest{
   static testMethod void FeedItemTriggerTestmethod(){
        
        /**Contact con = new Contact(LastName = 'test');
        insert con;
        FeedItem testobject = new FeedItem (Body = 'test',ParentId = con.Id);
        insert testobject;
        update testobject;
        delete testobject; 
        undelete testobject; 
         
        System.assertEquals('1','1');**/
    }
}